name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Test on ${{ matrix.os }} / Node ${{ matrix.node_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node_version: [20, 22]
        include:
          # Include Windows with only latest Node version to save time
          - os: windows-latest
            node_version: 22
      fail-fast: false
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint
        if: matrix.os == 'ubuntu-latest' # Only lint once

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Verify oclif manifest
        run: npm run prepack

      # Optional: Upload test results
      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}-node${{ matrix.node_version }}
          path: |
            test-results/
            coverage/
          retention-days: 7
